name: Module Build

env:
  GO_VERSION: '1.21'

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
  pull_request:
    branches:
      - master
    paths-ignore:
      - README.md

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go-version: [ '1.19', '1.20', '1.21' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Test
        run: go test -v -race ./... > test-results-${{ matrix.go-version }}.log

      - name: Upload Go test results
        uses: actions/upload-artifact@v3
        with:
          name: Test Results ${{ matrix.go-version }}
          path: test-results-${{ matrix.go-version }}.log

  build:
    runs-on: ubuntu-20.04
    needs: [ test ]

    strategy:
      matrix:
        go-version: [ '1.19', '1.20', '1.21' ]
  
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build
        run: go build -v ./...

  qa:
    runs-on: ubuntu-20.04
    needs: [ test, build ]
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Setup Code Climate
        uses: remarkablemark/setup-codeclimate@v1

      - name: Coverage
        run: |
          cc-test-reporter before-build
          go test -v -coverprofile c.out -coverpkg ./... -race
          cc-test-reporter after-build --coverage-input-type gocov --prefix $(go list) --exit-code $?
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: go
          
      - name: Build
        run: go build -v ./...

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:go"

