name: Module Release

env:
  GO_VERSION: '1.21'

on:
  push:
    tags:
      - v*.*.*

jobs:
  goreleaser:
    runs-on: ubuntu-20.04
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: release --clean

      - name: Run vangen
        run: |
          go install 4d63.com/vangen@latest
          ./scripts/vangen.sh
        env:
          VANGEN_TOKEN: ${{ secrets.VANGEN_TOKEN }}
