name: Go Module Release

on:
  push:
    branches:
      - master
    tags:
      - v*.*.*
    paths-ignore:
      - README.md
  pull_request:
    branches:
      - master
    paths-ignore:
      - README.md

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go-version: [ '1.19', '1.20', '1.21' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Test
        run: go test -v -race ./... > test-results-${{ matrix.go-version }}.log

      - name: Upload Go test results
        uses: actions/upload-artifact@v3
        with:
          name: Test Results ${{ matrix.go-version }}
          path: test-results-${{ matrix.go-version }}.log

  coverage:
    runs-on: ubuntu-20.04
    needs: [ test, build ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Setup Code Climate
        uses: remarkablemark/setup-codeclimate@v1

      - name: Coverage
        run: |
          cc-test-reporter before-build
          go test -v -coverprofile c.out -coverpkg ./... -race
          cc-test-reporter after-build --coverage-input-type gocov --prefix $(go list) --exit-code $?
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

  build:
    runs-on: ubuntu-20.04
    needs: [ test ]

    strategy:
      matrix:
        go-version: [ '1.19', '1.20', '1.21' ]
  
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build
        run: go build -v ./...

  vangen:
    runs-on: ubuntu-20.04
    needs: [ build ]
    if: ${{ github.ref_type == 'tag' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run vangen
        run: |
          go install 4d63.com/vangen@latest
          ./scripts/vangen.sh
        env:
          VANGEN_TOKEN: ${{ secrets.VANGEN_TOKEN }}

  release:
    runs-on: ubuntu-20.04
    needs: [ build ]
    if: ${{ github.ref_type == 'tag' }}

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Release
        run: |
          gh release create \
             --generate-notes \
             --title ${{ github.ref_name }} \
             ${{ github.ref_name }}
